version: 0.2



phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g nyc

  pre_build:
    commands:
      - echo Running Linting...
      - npm run lint  # Linting the source code
      - echo "Extracting PR number from commit message..."
      - PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '(?<=#)\d+')
      - echo "PR Number is $PR_NUMBER"


  build:
    commands:
      - echo Running Unit Tests...
      - npm run test --if-present
           - npm run coverage > coverage.log
      - COVERAGE=$(grep -oP 'Coverage:\s+\K\d+' coverage.log)
      - echo "Coverage is $COVERAGE%"
      # - echo Building the project...
      # - npm run build  # Building the React project

  post_build:
    commands:
      - |
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage is less than 80%, failing the build..."
          COMMENT="Coverage is $COVERAGE%, which is below the 80% threshold. Build failed."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\":\"$COMMENT\"}" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_PR_NUMBER/comments"
          exit 1
        else
          echo "Coverage is above 80%, proceeding..."
          COMMENT="Coverage is $COVERAGE%, build successful."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\":\"$COMMENT\"}" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$GITHUB_PR_NUMBER/comments"
        fi
      - echo Build completed on `date`
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://test-image-bkt/ --delete
      - echo Deployment to S3 completed.
      - echo Uploading Coverage to s3
      - aws s3 cp ./coverage/lcov-report s3://test-image-bkt/coverage/ --recursive


artifacts:
  files:
      - coverage.log
    # - build/**/* # Includes the build directory in artifacts
    # - coverage/**/*
  discard-paths: yes