version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running Linting...
      - npm run lint  # Linting the source code

  build:
    commands:
      - echo Running Unit Tests...
      - npm run test --if-present
      - echo Running Unit Coverage
      - npm run coverage # Run tests with NYC for coverage
      - echo "Checking coverage threshold..."
      - npx nyc check-coverage --branches 80 --functions 80 --lines 80 --statements 80 # Enforce 80% coverage

      # - npm run coverage # Running tests with coverage
      # - echo "Checking Code Coverage..."
      # - COVERAGE=$(grep -o '^[0-9]\+\.[0-9]\+' coverage/summary.txt | tail -n1)
      # - if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then echo "Code coverage below 80%"; exit 1; fi
      # - echo "Code coverage is $COVERAGE%."
      - echo Building the project...
      - npm run build  # Building the React project

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://test-image-bkt/ --delete
      - echo Deployment to S3 completed.
      - echo Uploading Coverage to s3
      - aws s3 cp ./coverage/lcov-report s3://test-image-bkt/coverage/ --recursive


artifacts:
  files:
    - build/**/* # Includes the build directory in artifacts
    - coverage/**/*
  discard-paths: yes